### ISSUE TITLE
How can I get only the "Parser" from a Data object?

### ISSUE THREAD

**Issue by domy95** [postmates/PMJSON#10]
I am new to iOS and need to read a very large JSON file and not load it into memory. I think that's Parser is the best solution for me

**Comment by kballard** [comment]
Yes, if you need to read in JSON but don't want the entire thing in memory at once, then the parser is the right approach. Looking at the code right now, the only way to create one from a `Data` is to copy a chunk of internal code from PMJSON. I'll push out a commit in a bit that adds a simple way to do this without copying code, and I'll update this ticket with more info at that time.

**Comment by kballard** [comment]
I just pushed c21e8b9dbf47db2f1a16d7aba453b7844c0cff10, which adds a method `JSON.parser(for:options:)`. This takes a `Data` and returns a `JSONParser<AnySequence<UnicodeScalar>>`. The `JSONParser` is a `Sequence` of `JSONEvent`s. Please let me know if you need anything else.

**Comment by PavelKorolev** [comment]
@kballard but this approach still works when full Data is in memory, right? What if we want to download large json file as sequence of byte chunks and parse them one by one? 
Is there any way to pass stream or push new Data chunk to parser so it can continue parsing?

**Comment by kballard** [comment]
You can construct a `JSONParser` out of any sequence that vends `UnicodeScalar`s. So you could write your own sequence that reads from successive `Data`s fed to it, and blocks if it's asked for a scalar while it's waiting for a new `Data`. The downside here is the parser will block when it runs out of data (because the sequence will block, because it has no choice). You could run the parser on a separate thread and then blocking would be ok (just don't spin up a hundred of these in parallel because blocked threads still consume memory resources). If you do go this route, be aware that you have to make your sequence thread-safe, because you need to be able to feed it `Data`s from a different thread than the parser is running on (because you need to feed it `Data`s while the parsing thread is blocked).

Unfortunately writing a JSON parser that can "pause" when it runs out of data and resume again later, without ever blocking the thread, is a lot of work and requires a very different design than PMJSON.
